application: oscarosl-test
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/img
  static_dir: assets/img

- url: /assets/fonts
  static_dir: assets/fonts

- url: /.*
  script: handlers.index.app

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
